### ISSUE TITLE
serialize function

### ISSUE THREAD

**Issue by Serginho** [jf3096/json-typescript-mapper#3]
When you map an object with custom property names:
`@JsonProperty('serverName')
myCustomName:number;`

It'd be usefull a function `serialize()` to reconvert again to server object.

**Comment by jf3096** [comment]
This is a viewmodel(vm) concept. If the project is develop independently with a front end developer and a backend programmer, we should assume there is no communication between them (because we could use vm concept to connect and adapt data and prevent data dependency).

Therefore, in this case, for a home page which require user info viewmodel,  and your personal profile page require a profile viewmodel. Since no communication between front end and back end, the backend developer develop one api for both pages and what front end developer needs to do is to adapt it (use json-typescript-mapper) and things done. From here, we could know that,

**This is one way, which is server data to client side data**
**one api raw data could map to many viewmodel. (1 to 1..*)**

Therefore, I didnt design for the other way round.

**Comment by sirudog** [comment]
Sorry to hear that it is a one way only solution. I also miss serialize() method. 
I made a quick research in this topic (json <=> ts entity mapping), and your solution is the most capable at the moment, but it lacks serialization by design, so I had to choose the second best library I found, which supports both directions of mapping...
Is it on your roadmap to support it?

**Comment by theBull** [comment]
Agreed that a `serialize()` method is needed. Your reasoning for "not assuming" that there is communication between front-end and back-end developers is based on *if the project is developed independently*, which is not necessarily a good hypothetical to use. Often times, projects may be developed independently, but both front-end and back-end developers are interchangeable, and may work in both roles throughout the project. Often times, there is only one developer working in both front-end and back-end roles. Aside from that, it is *very* common for typescript to be packaged back up into JSON to send updated data back to the API. I don't know of very many single-page applications where someone is just going to be pulling data from the server and not sending any updated data back.

**Comment by aequasi** [comment]
@jf3096 This implementation is still necessary for others, please consider this.

**Comment by jf3096** [comment]
I will get this done by this weekend since so many people suggesting the serialize. Thanks to @dankmo , he made a PR long ago about the serialize function. I have read it and I will validate it by this week. Go through unit tests and release it soon.

**Comment by jf3096** [comment]
please refer to the latest verson

**Comment by cryptiklemur** [comment]
index.d.ts doesnt have the new serialize method

**Comment by jf3096** [comment]
@aequasi thx for reminding, it fixed
